// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUJ2BKaC2RSbwb8mc1n4SKsWbtf8YpQc',
    appId: '1:40435673368:web:74c60c443f951b0dfa166d',
    messagingSenderId: '40435673368',
    projectId: 'cognix-c0a45',
    authDomain: 'cognix-c0a45.firebaseapp.com',
    storageBucket: 'cognix-c0a45.firebasestorage.app',
    measurementId: 'G-1MTJKTF8R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrvfTa8aGScFFzSmddq-m6JSb7nPTMMg',
    appId: '1:40435673368:android:346ac1107b23f1d0fa166d',
    messagingSenderId: '40435673368',
    projectId: 'cognix-c0a45',
    storageBucket: 'cognix-c0a45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8I-Tyg-4sK5bASONGpke4SlU6O9ip7Mk',
    appId: '1:40435673368:ios:36621b9a3416cb97fa166d',
    messagingSenderId: '40435673368',
    projectId: 'cognix-c0a45',
    storageBucket: 'cognix-c0a45.firebasestorage.app',
    iosClientId: '40435673368-3ll3e357fec0bmbp1fvjjibjuftojr1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.cognix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8I-Tyg-4sK5bASONGpke4SlU6O9ip7Mk',
    appId: '1:40435673368:ios:36621b9a3416cb97fa166d',
    messagingSenderId: '40435673368',
    projectId: 'cognix-c0a45',
    storageBucket: 'cognix-c0a45.firebasestorage.app',
    iosClientId: '40435673368-3ll3e357fec0bmbp1fvjjibjuftojr1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.cognix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAUJ2BKaC2RSbwb8mc1n4SKsWbtf8YpQc',
    appId: '1:40435673368:web:ffdaf5e6510bbe4cfa166d',
    messagingSenderId: '40435673368',
    projectId: 'cognix-c0a45',
    authDomain: 'cognix-c0a45.firebaseapp.com',
    storageBucket: 'cognix-c0a45.firebasestorage.app',
    measurementId: 'G-JPWWK6W69E',
  );
}
